/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react"
import { useGLTF } from "@react-three/drei"
import useNavStore from "../../state/navigation"
import gsap from "gsap"
import { useFrame } from "@react-three/fiber"

export default function Model(props) {
  const { nodes, materials } = useGLTF("/assets/model/code.glb")
  const nav = useNavStore()
  const group = useRef()
  const model = useRef()
  const dot1 = useRef()
  const dot2 = useRef()
  const dot3 = useRef()
  useFrame((state) => {
    const time = state.clock.elapsedTime
    model.current.position.z = Math.cos(time) * 0.05
    model.current.rotation.y = Math.sin(time) * 0.2

    dot1.current.position.z = Math.cos(time * 3) * 0.01
    dot2.current.position.z = Math.cos((time + 0.5) * 3) * 0.01
    dot3.current.position.z = Math.cos((time + 1.5) * 3) * 0.01
    // arrow.current.rotation.z = Math.sin(time * 5) * 0.1
  })
  useEffect(() => {
    if (nav.current === "webdev") {
      gsap.to(group.current.position, {
        z: 0,
        duration: 0.5,
        ease: "power2.out",
      })
    } else {
      gsap.to(group.current.position, {
        z: 1,
        duration: 0.5,
        ease: "power2.out",
      })
    }
  }, [nav.current])
  return (
    <group
      {...props}
      dispose={null}
      position={[-3.2, -1.1, 2.5]}
      rotation={[Math.PI / 2, -0.1, 0.5]}
    >
      <group ref={group}>
        <group ref={model}>
          <mesh geometry={nodes.Brackets.geometry}>
            <meshStandardMaterial color="purple" />
          </mesh>
          <mesh geometry={nodes.Dot1.geometry} ref={dot1}>
            <meshStandardMaterial color="white" />
          </mesh>
          <mesh geometry={nodes.Dot2.geometry} ref={dot2}>
            <meshStandardMaterial color="white" />
          </mesh>
          <mesh geometry={nodes.Dot3.geometry} ref={dot3}>
            <meshStandardMaterial color="white" />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/assets/model/code.glb")
