/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import TransitionMatcapMaterial from "./TransitionMatcapMaterial"
export default function Cone(props) {
  const { nodes, materials } = useGLTF("/assets/model/cone.glb")
  const cone = useRef()
  useFrame((state) => {
    const time = state.clock.elapsedTime
    cone.current.position.y = -Math.sin(time / 2) * 0.2
    cone.current.rotation.x += 0.02
    cone.current.rotation.z += 0.02
  })
  return (
    <group {...props} dispose={null} ref={cone}>
      <mesh geometry={nodes.Cone.geometry}>
        <TransitionMatcapMaterial transitionDelay={0.12} />
      </mesh>
    </group>
  )
}

useGLTF.preload("/assets/model/cone.glb")
