/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react"
import { useGLTF } from "@react-three/drei"
import useNavStore from "../../state/navigation"
import gsap from "gsap"
import { useFrame } from "@react-three/fiber"
export default function Model(props) {
  const { nodes, materials } = useGLTF("/assets/model/jslogo.glb")
  const nav = useNavStore()
  const group = useRef()
  const model = useRef()
  useFrame((state) => {
    const time = state.clock.elapsedTime
    model.current.position.z = Math.sin(time) * 0.05
    model.current.rotation.y = Math.sin(time) * 0.2

    // arrow.current.rotation.z = Math.sin(time * 5) * 0.1
  })
  useEffect(() => {
    if (nav.current === "webdev") {
      gsap.to(group.current.position, {
        z: 0,
        duration: 0.5,
        ease: "power2.out",
      })
    } else {
      gsap.to(group.current.position, {
        z: -1,
        duration: 0.5,
        ease: "power2.out",
      })
    }
  }, [nav.current])
  return (
    <group
      {...props}
      dispose={null}
      position={[-2.2, 0.65, 3]}
      rotation={[Math.PI / 2, -0.1, 0.5]}
    >
      <group ref={group}>
        <group ref={model}>
          <mesh geometry={nodes.Base.geometry}>
            <meshStandardMaterial color="yellow" />
          </mesh>
          <mesh geometry={nodes.Text.geometry}>
            <meshStandardMaterial color="black" />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/assets/model/jslogo.glb")
