/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import useNavStore from "../../state/navigation"
import gsap from "gsap"
export default function Model(props) {
  const group = useRef()
  const selection = useRef()
  const nav = useNavStore()
  const { nodes, materials } = useGLTF("/assets/model/toggle.glb")

  useFrame((state) => {
    const time = state.clock.elapsedTime
    group.current.position.z = Math.cos(time) * 0.05
    group.current.rotation.y = Math.sin(time) * 0.2

    selection.current.position.x = Math.sin(time) * 0.1 + 0.1
  })
  useEffect(() => {
    if (nav.current === "uiux") {
      gsap.to(group.current.position, {
        y: 0.38,
        duration: 0.5,
        ease: "power2.out",
      })
    } else {
      gsap.to(group.current.position, {
        y: 2,
        duration: 0.5,
        ease: "power2.out",
      })
    }
  }, [nav.current])
  return (
    <group
      {...props}
      dispose={null}
      position={[-3.1, 0.38, 2.7]}
      scale={[0.75, 0.75, 0.75]}
      rotation={[Math.PI / 2, 0.4, 0.5]}
    >
      <group ref={group}>
        <mesh
          geometry={nodes.Selection.geometry}
          ref={selection}
          position={[0, 0.05, 0]}
        >
          <meshStandardMaterial color="orange" />
        </mesh>
        <mesh geometry={nodes.Base.geometry}>
          <meshStandardMaterial color="white" />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload("/assets/model/toggle.glb")
