import React from "react"
import Head from "next/head"
import styles from "../../styles/Project.module.css"

import Intro from "../../src/components/Project/Intro"
import Picture from "../../src/components/Project/Picture"
import SectionHeader from "../../src/components/Project/SectionHeader"
import Paragraph from "../../src/components/Project/Paragraph"
import NextProject from "../../src/components/Project/NextProject"

import HeaderImage from "../../public/assets/img/namet/00_header.png"
import Current from "../../public/assets/img/namet/01_current.png"
import Interview from "../../public/assets/img/namet/03_interview.png"
import UserFlow from "../../public/assets/img/namet/04_user_flow.png"
import Wireframe from "../../public/assets/img/namet/05_wireframe.png"
import Codes from "../../public/assets/img/namet/06_codes.png"
import Prototype from "../../public/assets/img/namet/07_prototype.png"
import Example from "../../public/assets/img/namet/08_example.png"
import Data from "../../public/assets/img/namet/09_data.png"
import Sheet from "../../public/assets/img/namet/10_sheets.png"

const Namet = () => {
  return (
    <div className={styles["container"]}>
      <Head>
        <title>WEIJIEFU DESIGN</title>
        <meta name="description" content="Weijie Fu Design Portfolio" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro
        year={2022}
        title={"Namet"}
        summary={[
          "Namet is a figma plugin I created for Loupe (previously Atelier Technology). It allows users to name frames and components in a programmatic way to keep consistent naming convensions across the team. The naming data was centralized as the data base for analysing site maps, tracking changes and other product operations.",
        ]}
        roles={["Wireframing", "Programming"]}
      />
      <Picture layout="center" src={HeaderImage} alt="Header Image" />
      <SectionHeader
        index="01"
        title="Problem Space"
        text={[
          "Have you also struggled with having 10 different naming styles in you projects, when the assets are generated by different designers? And some use '-', some using '/' or  nothing at all to convey a vague hierarchy in their own mind? Or when your collaborator verbally agreed with you what naming style we should use but eventually you have to rename them one by one before documentation?",
          "It's nice to remember every small nuances in your team. But sometimes our memory is just not that reliable. And you wish there were a magic spell just populate the name for me.",
        ]}
      />

      <Picture layout="center" src={Current} alt="Current Situation" />
      <Paragraph
        title="Goals"
        text={[
          {
            style: "dark",
            content:
              "The goal for this project is simple. To create a tool that can help the team have consistent naming convension.",
          },
        ]}
      />

      <SectionHeader
        index="02"
        title="Research"
        icons={[
          {
            icon: ["fa-solid", "fa-clipboard-question"],
            label: "Interview",
          },
          {
            icon: ["fa-solid", "fa-timeline"],
            label: "User Flow",
          },
          {
            icon: ["fa-solid", "fa-mobile-retro"],
            label: "Wireframe",
          },
          {
            icon: ["fab", "figma"],
            label: "Figma API",
          },
        ]}
      />

      <Paragraph
        title="Interview"
        text={[
          {
            style: "dark",
            content:
              "When I brought up the idea to the team, they were all onboard without any heisitation. But what exactly should we build? For the first step, I interviewed the design team members and product ops, in order to gather the figure out the real pain point we are trying to solve.",
          },
          {
            style: "dark",
            content:
              "The number one feedback is surprisingly not the lack of tools or bad memory to apply naming convention, but the naming convention on which was never agreed across the board.",
          },

          {
            style: "dark",
            content:
              "After serveral rounds of discussion, we decided on our new naming convention: ",
          },
          {
            style: "light",
            content: "1. Epic / Feature / Flow / Screen - Block",
          },
          {
            style: "light",
            content: "2. Use capital case",
          },
          {
            style: "light",
            content: "3. Use '/' for seperation",
          },
        ]}
      />

      <Picture layout="center" src={Interview} alt="Current Situation" />

      <Paragraph
        title="User Flow"
        text={[
          {
            style: "dark",
            content:
              "We streamlined the actions and defined how data flows through each domain.",
          },
        ]}
      />
      <Picture layout="center" src={UserFlow} alt="User Flow" />

      <Paragraph
        title="Wireframe"
        text={[
          {
            style: "dark",
            content:
              "Thanks to Figma API documentation, after a brief reading, I was able to put together a wireframe that complies with the functionality Figma provides. The plugin contains lists of branches in each hierarchy and designers can click on the screen or block level to apply the correct naming.",
          },
        ]}
      />
      <Picture layout="center" src={Wireframe} alt="Wireframe" />

      <SectionHeader index="03" title="Get Hands Dirty" />

      <Paragraph
        title="Create Figma Plugin"
        text={[
          {
            style: "dark",
            content:
              "Create Figma Plugin is a great tool created by the community to easily scaffold the plugin script with Preact.",
          },
        ]}
      />

      <Picture layout="center" src={Codes} alt="Codes" />
      <Paragraph
        text={[
          {
            style: "dark",
            content:
              "A set of ready-made components is also availble to create plugins that are also compliant with the Figma UI style.",
          },
        ]}
      />
      <Picture layout="center" src={Prototype} alt="Prototype" />
      <Paragraph
        title="Google Sheets API"
        text={[
          {
            style: "dark",
            content:
              "For the database, I decided to deploy an Apps Script in Google Sheets to handle GET and POST requests. Using Google Sheets enables us to easily visualize and manage the data.",
          },
        ]}
      />

      <Picture layout="center" src={Sheet} alt="Google Sheets App Script" />

      <Paragraph
        title="Happy User Happy Life"
        text={[
          {
            style: "dark",
            content:
              "Now all of our new projects are using the plugin to name frames and components programmatically. And it's easier than ever to understand the components hierarchy.",
          },
        ]}
      />
      <Picture layout="center" src={Example} alt="Example" />
      <Paragraph
        title="Mine That Data"
        text={[
          {
            style: "dark",
            content:
              "The data we collected are further used by product operation to monitor changes, generate size maps and create user guides in Pendo. And there is a lot more to discover!",
          },
        ]}
      />
      <Picture layout="center" src={Data} alt="Data" />

      <NextProject project="Appitur" />
    </div>
  )
}

export default Namet
